# Generated by Django 5.2.7 on 2025-11-04 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_course_student_remove_borrowrecord_book_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_code',
            field=models.CharField(max_length=20, unique=True, verbose_name='課號'),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=100, verbose_name='課名'),
        ),
        migrations.AlterField(
            model_name='course',
            name='teacher',
            field=models.CharField(max_length=50, verbose_name='任課老師'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='final_score',
            field=models.FloatField(default=0, verbose_name='期末分數'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='midterm_score',
            field=models.FloatField(default=0, verbose_name='期中分數'),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=100, verbose_name='學生姓名'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.CharField(max_length=20, unique=True, verbose_name='學號'),
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('student', 'course')},
        ),
    ]
